@ToDoApi_HostAddress = https://localhost:7006

POST {{ToDoApi_HostAddress}}/todo
Content-Type: application/json

{
  "Name":"buy groceries",
  "isCompleted":false
}

###

GET {{ToDoApi_HostAddress}}/todo

###

GET {{ToDoApi_HostAddress}}/todo/2

###

GET {{ToDoApi_HostAddress}}/todo/completed

###

DELETE {{ToDoApi_HostAddress}}/todo/2

###

PUT {{ToDoApi_HostAddress}}/todo/1
Content-Type: application/json

{
  "isCompleted":true
}

